// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DetectorClient is the client API for Detector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DetectorClient interface {
	Detect(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type detectorClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectorClient(cc grpc.ClientConnInterface) DetectorClient {
	return &detectorClient{cc}
}

func (c *detectorClient) Detect(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/udetect.Detector/Detect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectorServer is the server API for Detector service.
// All implementations must embed UnimplementedDetectorServer
// for forward compatibility
type DetectorServer interface {
	Detect(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedDetectorServer()
}

// UnimplementedDetectorServer must be embedded to have forward compatible implementations.
type UnimplementedDetectorServer struct {
}

func (UnimplementedDetectorServer) Detect(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detect not implemented")
}
func (UnimplementedDetectorServer) mustEmbedUnimplementedDetectorServer() {}

// UnsafeDetectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetectorServer will
// result in compilation errors.
type UnsafeDetectorServer interface {
	mustEmbedUnimplementedDetectorServer()
}

func RegisterDetectorServer(s grpc.ServiceRegistrar, srv DetectorServer) {
	s.RegisterService(&Detector_ServiceDesc, srv)
}

func _Detector_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectorServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/udetect.Detector/Detect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectorServer).Detect(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Detector_ServiceDesc is the grpc.ServiceDesc for Detector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Detector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "udetect.Detector",
	HandlerType: (*DetectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _Detector_Detect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol/protocol.proto",
}
